version: "3.7"
services:
  primeo.backend:
    build:
      args:
        user: primeo
        uid: ${WWWUSER}
      context: ./
      dockerfile: Dockerfile
    image: primeo
    container_name: primeo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - primeo
  db:
    image: mysql:8.0
    container_name: primeo-db
    restart: unless-stopped
    ports:
    - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    networks:
      - primeo
  nginx:
    image: nginx:alpine
    container_name: primeo-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - primeo
networks:
  primeo:
    driver: bridge